name: Group 2 CI

on:
  push:
    branches:
      - group2
  pull_request:
    branches:
      - group2

jobs:

  seqkit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment (cached)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: 01_GitHub/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run count step
        shell: micromamba-shell {0}
        run: bash 01_GitHub/scripts/02-summarize-seqs.sh 01_GitHub/data test_output/seq_counts.tsv 8